version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - huggingface_cache:/root/.cache/huggingface
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  huggingface_cache: 