version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - huggingface_cache:/root/.cache/huggingface
      - ./output:/app/output
    env_file:
      - .env

volumes:
  huggingface_cache: 